### ISSUE TITLE
Tag release images also with base versions

### ISSUE THREAD

**Issue by pohly** [kubernetes-csi/csi-release-tools#6]
Original proposal from @bertinatto in https://github.com/kubernetes-csi/driver-registrar/issues/77:
> With CSI becoming GA in Kubernetes v1.13, it would be interesting to provide CSI driver developers with a mechanism to have their sidecar images always updated without having to be aware of new builds of those images.

This can be achieved by also tagging a `vA.B.C` release image as `vA.B` and `vA`.

Users of those tags must be aware of the caveat that automatically updating by always pulling the latest `vA` image may miss some changes between releases, for example:
- RBAC rule changes
- new, optional features that need to be enabled via command line changes

**Comment by msau42** [comment]
I don't know about `vA`. There could be signficant changes and would not guarantee a stable upgrade. 

I'm fine without the stable designation.

**Comment by kfox1111** [comment]
This is an antipattern I think. This puts the onus on those deploying the driver to ensure that through the lifecycle, that no new nodes come online or get restarted, as an upgraded version might get released upstream and the cluster may then have a version skew, leading to hard to find issues. There is no tooling around to ensure consistency in kubernetes outside of ensuring a tag is atomic. Alternately the deployer can replicate the image back to a tagged version which has all the difficulty your trying to avoid. So either way, its pushing difficult work onto the deployer.

Part of the issue I think is the avoidance of higher level packaging tools that should be able to help with this. One solution might be to release a helm library chart that contains references to the most up to date images. You can then nest that in your own csi driver deployment chart and it will contain up to date versions.

**Comment by msau42** [comment]
That's a good point. It will be a challenge to get a consistent version to validate and test

**Comment by pohly** [comment]
@kfox1111 I myself have been undecided and had my concerns (see https://github.com/kubernetes-csi/driver-registrar/issues/77#issuecomment-442098715), but both @wongma7 and @bertinatto seemed to be willing to take the risk.

By offering the two additional tags, we basically let users choose how carefully they want to monitor their deployments. We can strongly warn against doing it while still offering the choice, or we can take a hard stance and argue that this never makes sense and don't set the additional tags.

**Comment by pohly** [comment]
Michelle Au <notifications@github.com> writes:
> I don't know about `vA`. There could be signficant changes and would
> not guarantee a stable upgrade.

`vA` would cover updates from, for example, v1.1.0 to v1.2.0. By
definition, the update must be backwards-compatible, so this should be
safe (or at least as safe as any unchecked, automatic update can
be).

If we have significant changes that prevent a stable update, we should
bump the major version number.

BTW, the decentralized release process (
https://github.com/pohly/csi-release/pull/1/commits/fa2108276c711a686c46dbf27fd2b0000d152eb6)
hinges strongly on the ability to update individual components because
the message that only a certain version combination is considered "the
stable release" becomes weaker.

**Comment by kfox1111** [comment]
There's a couple of different actors here. so "users" is ambiguous. Like I mentioned above, there's csi driver packagers, and csi driver deployers.

packagers will generally want to do the easiest thing which would be to not care about the version and just let it float. I get the desire. I'm not unsympathetic.

deployers need to be very careful then, but as kubernetes is still fairly new, not everyone realizes that while k8s provides tooling to allow consistent deployments, it can easily be misconfigured so that it doesn't. You find it by mistake later, and can spend considerable time/effort/money trying to find the subtle bug. I think this a footgun for deployers that we shouldn't make easy to have happen. We also run the risk of accidentally teaching users to do the wrong thing, as it would be the common thing.

So, I'd recommend we try and find a packaging/k8s level solution to it rather then a pure container tagging workaround that just shifts the problem and not solves it.

For example, an operator that watched/updated daemonset's image tags. or a helm library chart. or if k8s is willing, an enhanced version of daemonset that captured the shasum of the image in the podspec and always used the sha in the pods could solve it. that one could safely be used with the tagging scheme from this issue. 

This particular issue is not specific to csi sidecars in any way. How to find the newest version of things and do rolling upgrades with it, etc is a general issue to all of k8s deployed things.

**Comment by pohly** [comment]
/remove-lifecycle stale

With our current definition of "compatible binaries" (= must work in an existing deployment without updating RBAC rules) one of my own concerns regarding tagging base versions is gone, because a v1.1.1 image must work in a deployment that was originally created for v1.1.0.

Whether it makes sense to pull a potentially changing image tag like "v1.1" is still subjective.

Should we reconsider whether we want to support it by creating such tags?
